# site settings
title: Alexander
subtitle: Young
email: alexphillipyoung@gmail.com
description: This site is under construction
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/alexpyoung
instagram_url: https://instagram.com/alexpyoung
linkedin_url: https://www.linkedin.com/in/alexphillipyoung

# build settings
markdown: kramdown

sass:
  style: compressed
