title: Alex Young

email: alexphillipyoung@gmail.com
github: https://github.com/alexpyoung
linkedin: https://www.linkedin.com/in/alexphillipyoung
twitter: https://twitter.com/alexpyoung

markdown: kramdown
theme: minima
sass:
    sass_dir: styles
    style: compressed
