title: Alex Young

nav:
    - title: Home
      href: /
    - title: Photos
      href: /photos

links:
    - href: https://www.instagram.com/alexpyoung
      src: /assets/instagram.svg
    - href: https://www.linkedin.com/in/alexphillipyoung
      src: /assets/linkedin.svg
    - href: https://github.com/alexpyoung
      src: /assets/github.svg
    - href: mailto:bold.plan3318@fastmail.com
      src: /assets/email.svg

photos:
    - /assets/photos/Trinidad.jpeg
    - /assets/photos/HalfDome1.jpeg
    - /assets/photos/SandDunes.jpeg
    - /assets/photos/LimekilnCreekBridge.jpeg
    - /assets/photos/Glacier.jpeg
    - /assets/photos/Brian.jpeg
    - /assets/photos/JudasTree.jpeg
    - /assets/photos/Polygons.jpeg
    - /assets/photos/TenSleep.jpeg
    - /assets/photos/NanLien.jpeg
    - /assets/photos/HalfDome0.jpeg
    - /assets/photos/Roscoe.jpeg
    - /assets/photos/Malecon.jpeg
    - /assets/photos/Sarah.jpeg
    - /assets/photos/KipsBay.jpeg
    - /assets/photos/Tetons.jpeg
    - /assets/photos/Bee.jpeg
    - /assets/photos/PfiefferBeach.jpeg
    - /assets/photos/PuentedeBacunayagua.jpeg
    - /assets/photos/Rain.jpeg
    - /assets/photos/Matt.jpeg
    - /assets/photos/WTC.jpeg

markdown: kramdown
theme: minima
sass:
    sass_dir: styles
    style: compressed
