application: alex-young
version: 2
runtime: php
api_version: 1
threadsafe: true

default_expiration: "7d 0h"

skip_files:
- (.*/)?.*/node_modules/.+ 
- (.*/)?.*/src/.+
- (.*/)?.*/gruntfile\.js
- (.*/)?.*/todo\.txt

handlers:
# - url: /robots.txt
#   static_files: robots.txt
#   upload: robots.txt 
  
- url: /Alexander_Young_Resume.pdf
  static_files: build/Alexander_Young_Resume.pdf
  upload: build/Alexander_Young_Resume.pdf

- url: /css
  static_dir: build/css

- url: /img
  static_dir: build/img  

- url: /js
  static_dir: build/js  

- url: /(.*\.(gif|png|jpg|ico|js|css|eot|svg|ttf|woff))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|eot|svg|ttf|woff))

- url: /(.+\.php)$
  script: build/\1

- url: /
  script: build/index.php
