application: alex-young
version: 2
runtime: php
api_version: 1
threadsafe: true

default_expiration: "7d 0h"

skip_files:
- (.*/)?.*/node_modules/.+ 
- (.*/)?.*/src/.+
- (.*/)?.*/gruntfile\.js
- (.*/)?.*/todo\.txt
# - ^(.*/)?#.*#
# - ^(.*/)?.*~
# - ^(.*/)?.*\.py[co]
# - ^(.*/)?.*/RCS/.*
# - ^(.*/)?\..*
# - ^(.*/)?.*/nbproject/.*
#- ^(.*/)?.*/images/.*

handlers:
# - url: /robots.txt
#   static_files: robots.txt
#   upload: robots.txt 
  
# - url: /Alexander\ Young\ -\ Resume.pdf
#   static_dir: build/Alexander\ Young\ -\ Resume.pdf
#   upload: build/Alexander\ Young\ -\ Resume.pdf

- url: /css
  static_dir: build/css

- url: /img
  static_dir: build/img  

- url: /js
  static_dir: build/js  

- url: /partials
  static_dir: build/partials
  application_readable: true

- url: /templates
  static_dir: build/templates
  application_readable: true  

- url: /utils
  static_dir: build/utils
  application_readable: true

- url: /(.*/)?.*/mustache
  static_dir: /mustache
  application_readable: true

- url: /(.*\.(gif|png|jpg|ico|js|css|eot|svg|ttf|woff))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|eot|svg|ttf|woff))

- url: /(.+\.php)$
  script: build/\1

- url: /
  script: build/index.php
